### ISSUE TITLE
UI: Quiz-like interface for students to learn

### ISSUE THREAD

**Issue by NoahCardoza** [NoahCardoza/VocabTiles#7]
- [x] Menu view
- [x] Level 1 game view
- [x] Level 2 game view
- [x] Level 3 game view

**Comment by naomiquinones** [comment]
Here is a link to [how the flow could go on a mobile device](https://www.figma.com/proto/KkeAOSztn25PzZdGnZVrjV/Vocab-Tiles?node-id=7%3A2&scaling=scale-down).

### Start screen
![Start screen](https://user-images.githubusercontent.com/52065567/95444842-1f5ab900-0913-11eb-9388-90ec13b2acb1.png)

### Menu
![iPhone 8 - Menu](https://user-images.githubusercontent.com/52065567/95444867-2b467b00-0913-11eb-97a2-981e41f5c7f3.png)

### Easy level
![iPhone 8 - Easy](https://user-images.githubusercontent.com/52065567/95444900-35687980-0913-11eb-9e18-967e73395657.png)

### Hard level
![iPhone 8 - Hard](https://user-images.githubusercontent.com/52065567/95444924-3a2d2d80-0913-11eb-9b4b-9e5506e82891.png)
